apiVersion: v1
kind: Service
metadata:
  # service name
  name: hello-k8s-service
spec:
  selector:
    # pod name
    app: hello-k8s-pod
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
